services:
  postgres:
    image: postgres:16
    container_name: ehpad_postgres
    restart: always
    environment:
      POSTGRES_USER: ehpad_user
      POSTGRES_PASSWORD: ehpad_password
      POSTGRES_DB: ehpad_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/02_import_csv.sql:/docker-entrypoint-initdb.d/02_import_csv.sql
      - ./database/03_seed_users.sql:/docker-entrypoint-initdb.d/03_seed_users.sql
      - ./database/04_views.sql:/docker-entrypoint-initdb.d/04_views.sql
      - ./data:/data

volumes:
  postgres_data:
