services:

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/config/mosquitto.conf
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: ehpad_dashboard
    ports:
      - "8080:80"
    volumes:
      # Si tu as mis les fichiers dans un dossier "frontend", laisse cette ligne :
      - ./frontend:/usr/share/nginx/html:ro 
      # (Si tu as tout laissé à la racine, remplace "./frontend" par ".")
    depends_on:
      - mqtt-broker
      - backend-ia

  redis-cache:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend-ia:
    build: ./backend_IA
    platform: linux/amd64
    container_name: backend_ia
    depends_on:
      - mqtt-broker
      - redis-cache
      - postgres
    restart: on-failure

  ollama:
    image: ollama/ollama
    container_name: ollama_llm
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped

  simulateur-vitaux:
    build: ./simulateur
    container_name: ehpad_simulator_vitaux
    depends_on:
      - mqtt-broker
    volumes:
      - ./data:/app/data
    restart: on-failure

  simulateur-capteurs:
    build: ./capteurs
    container_name: ehpad_simulator_capteurs
    depends_on:
      - mqtt-broker
    volumes:
      - ./data:/app/data
    restart: on-failure

  fastapi:
    build: ./api
    container_name: ehpad_fastapi
    ports:
      "8000:8000"
    depends_on:
      postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: ehpad_postgres
    restart: always
    environment:
      POSTGRES_USER: ehpad_user
      POSTGRES_PASSWORD: ehpad_password
      POSTGRES_DB: ehpad_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/02_import_csv.sql:/docker-entrypoint-initdb.d/02_import_csv.sql
      - ./database/03_seed_users.sql:/docker-entrypoint-initdb.d/03_seed_users.sql
      - ./database/04_views.sql:/docker-entrypoint-initdb.d/04_views.sql
      - ./data:/data


