-- =========================================================
-- 03_seed_users.sql
-- Comptes de démonstration : 1 admin, 10 soignants,
-- 40 comptes famille reliés aux 40 résidents.
-- =========================================================

INSERT INTO users (firstname, lastname, email, password_hash, role, phone)
VALUES
('Admin', 'EHPAD', 'admin@ehpad.local', 'hashed_password_demo', 'admin', '0600000000'),
('Claire', 'Durand', 'claire.durand@ehpad.local', 'hashed_password_demo', 'nurse', '0600000001'),
('Paul', 'Moreau', 'paul.moreau@ehpad.local', 'hashed_password_demo', 'doctor', '0600000002'),
('Sophie', 'Leroy', 'sophie.leroy@ehpad.local', 'hashed_password_demo', 'nurse', '0600000003'),
('Karim', 'Benali', 'karim.benali@ehpad.local', 'hashed_password_demo', 'caregiver', '0600000004'),
('Nadia', 'Rousseau', 'nadia.rousseau@ehpad.local', 'hashed_password_demo', 'nurse', '0600000005'),
('Thomas', 'Petit', 'thomas.petit@ehpad.local', 'hashed_password_demo', 'doctor', '0600000006'),
('Julie', 'Garnier', 'julie.garnier@ehpad.local', 'hashed_password_demo', 'caregiver', '0600000007'),
('Antoine', 'Faure', 'antoine.faure@ehpad.local', 'hashed_password_demo', 'nurse', '0600000008'),
('Marine', 'Chevalier', 'marine.chevalier@ehpad.local', 'hashed_password_demo', 'caregiver', '0600000009'),
('Olivier', 'Masson', 'olivier.masson@ehpad.local', 'hashed_password_demo', 'doctor', '0600000010');

INSERT INTO users (firstname, lastname, email, password_hash, role, phone)
VALUES
('Camille', 'Martin', 'camille.martin@mail.local', 'hashed_password_demo', 'family', '0610000001'),
('Lucas', 'Bernard', 'lucas.bernard@mail.local', 'hashed_password_demo', 'family', '0610000002'),
('Emma', 'Robert', 'emma.robert@mail.local', 'hashed_password_demo', 'family', '0610000003'),
('Hugo', 'Richard', 'hugo.richard@mail.local', 'hashed_password_demo', 'family', '0610000004'),
('Léa', 'Petit', 'lea.petit@mail.local', 'hashed_password_demo', 'family', '0610000005'),
('Nathan', 'Durand', 'nathan.durand@mail.local', 'hashed_password_demo', 'family', '0610000006'),
('Chloé', 'Moreau', 'chloe.moreau@mail.local', 'hashed_password_demo', 'family', '0610000007'),
('Louis', 'Simon', 'louis.simon@mail.local', 'hashed_password_demo', 'family', '0610000008'),
('Manon', 'Laurent', 'manon.laurent@mail.local', 'hashed_password_demo', 'family', '0610000009'),
('Gabriel', 'Michel', 'gabriel.michel@mail.local', 'hashed_password_demo', 'family', '0610000010'),
('Inès', 'Lefevre', 'ines.lefevre@mail.local', 'hashed_password_demo', 'family', '0610000011'),
('Arthur', 'Garcia', 'arthur.garcia@mail.local', 'hashed_password_demo', 'family', '0610000012'),
('Sarah', 'David', 'sarah.david@mail.local', 'hashed_password_demo', 'family', '0610000013'),
('Jules', 'Bertrand', 'jules.bertrand@mail.local', 'hashed_password_demo', 'family', '0610000014'),
('Clara', 'Roux', 'clara.roux@mail.local', 'hashed_password_demo', 'family', '0610000015'),
('Noah', 'Vincent', 'noah.vincent@mail.local', 'hashed_password_demo', 'family', '0610000016'),
('Alice', 'Fournier', 'alice.fournier@mail.local', 'hashed_password_demo', 'family', '0610000017'),
('Raphaël', 'Morel', 'raphael.morel@mail.local', 'hashed_password_demo', 'family', '0610000018'),
('Zoé', 'Girard', 'zoe.girard@mail.local', 'hashed_password_demo', 'family', '0610000019'),
('Tom', 'Andre', 'tom.andre@mail.local', 'hashed_password_demo', 'family', '0610000020'),
('Eva', 'Lemoine', 'eva.lemoine@mail.local', 'hashed_password_demo', 'family', '0610000021'),
('Mathis', 'Mercier', 'mathis.mercier@mail.local', 'hashed_password_demo', 'family', '0610000022'),
('Louise', 'Dupuis', 'louise.dupuis@mail.local', 'hashed_password_demo', 'family', '0610000023'),
('Enzo', 'Lambert', 'enzo.lambert@mail.local', 'hashed_password_demo', 'family', '0610000024'),
('Mila', 'Bonnet', 'mila.bonnet@mail.local', 'hashed_password_demo', 'family', '0610000025'),
('Liam', 'Francois', 'liam.francois@mail.local', 'hashed_password_demo', 'family', '0610000026'),
('Anna', 'Martinez', 'anna.martinez@mail.local', 'hashed_password_demo', 'family', '0610000027'),
('Ethan', 'Legrand', 'ethan.legrand@mail.local', 'hashed_password_demo', 'family', '0610000028'),
('Jeanne', 'Guerin', 'jeanne.guerin@mail.local', 'hashed_password_demo', 'family', '0610000029'),
('Maël', 'Boyer', 'mael.boyer@mail.local', 'hashed_password_demo', 'family', '0610000030'),
('Lucie', 'Renaud', 'lucie.renaud@mail.local', 'hashed_password_demo', 'family', '0610000031'),
('Sacha', 'Muller', 'sacha.muller@mail.local', 'hashed_password_demo', 'family', '0610000032'),
('Nina', 'Henry', 'nina.henry@mail.local', 'hashed_password_demo', 'family', '0610000033'),
('Adam', 'Perrin', 'adam.perrin@mail.local', 'hashed_password_demo', 'family', '0610000034'),
('Lina', 'Marchand', 'lina.marchand@mail.local', 'hashed_password_demo', 'family', '0610000035'),
('Victor', 'Dufour', 'victor.dufour@mail.local', 'hashed_password_demo', 'family', '0610000036'),
('Rose', 'Blanchard', 'rose.blanchard@mail.local', 'hashed_password_demo', 'family', '0610000037'),
('Maxime', 'Renard', 'maxime.renard@mail.local', 'hashed_password_demo', 'family', '0610000038'),
('Agathe', 'Barbier', 'agathe.barbier@mail.local', 'hashed_password_demo', 'family', '0610000039'),
('Baptiste', 'Colin', 'baptiste.colin@mail.local', 'hashed_password_demo', 'family', '0610000040');

INSERT INTO family_access (user_id, resident_id, relationship)
VALUES
((SELECT id FROM users WHERE email = 'camille.martin@mail.local'), 'R1', 'daughter'),
((SELECT id FROM users WHERE email = 'lucas.bernard@mail.local'), 'R2', 'son'),
((SELECT id FROM users WHERE email = 'emma.robert@mail.local'), 'R3', 'daughter'),
((SELECT id FROM users WHERE email = 'hugo.richard@mail.local'), 'R4', 'son'),
((SELECT id FROM users WHERE email = 'lea.petit@mail.local'), 'R5', 'granddaughter'),
((SELECT id FROM users WHERE email = 'nathan.durand@mail.local'), 'R6', 'grandson'),
((SELECT id FROM users WHERE email = 'chloe.moreau@mail.local'), 'R7', 'daughter'),
((SELECT id FROM users WHERE email = 'louis.simon@mail.local'), 'R8', 'son'),
((SELECT id FROM users WHERE email = 'manon.laurent@mail.local'), 'R9', 'niece'),
((SELECT id FROM users WHERE email = 'gabriel.michel@mail.local'), 'R10', 'nephew'),
((SELECT id FROM users WHERE email = 'ines.lefevre@mail.local'), 'R11', 'daughter'),
((SELECT id FROM users WHERE email = 'arthur.garcia@mail.local'), 'R12', 'son'),
((SELECT id FROM users WHERE email = 'sarah.david@mail.local'), 'R13', 'daughter'),
((SELECT id FROM users WHERE email = 'jules.bertrand@mail.local'), 'R14', 'son'),
((SELECT id FROM users WHERE email = 'clara.roux@mail.local'), 'R15', 'granddaughter'),
((SELECT id FROM users WHERE email = 'noah.vincent@mail.local'), 'R16', 'grandson'),
((SELECT id FROM users WHERE email = 'alice.fournier@mail.local'), 'R17', 'daughter'),
((SELECT id FROM users WHERE email = 'raphael.morel@mail.local'), 'R18', 'son'),
((SELECT id FROM users WHERE email = 'zoe.girard@mail.local'), 'R19', 'niece'),
((SELECT id FROM users WHERE email = 'tom.andre@mail.local'), 'R20', 'nephew'),
((SELECT id FROM users WHERE email = 'eva.lemoine@mail.local'), 'R21', 'daughter'),
((SELECT id FROM users WHERE email = 'mathis.mercier@mail.local'), 'R22', 'son'),
((SELECT id FROM users WHERE email = 'louise.dupuis@mail.local'), 'R23', 'daughter'),
((SELECT id FROM users WHERE email = 'enzo.lambert@mail.local'), 'R24', 'son'),
((SELECT id FROM users WHERE email = 'mila.bonnet@mail.local'), 'R25', 'granddaughter'),
((SELECT id FROM users WHERE email = 'liam.francois@mail.local'), 'R26', 'grandson'),
((SELECT id FROM users WHERE email = 'anna.martinez@mail.local'), 'R27', 'daughter'),
((SELECT id FROM users WHERE email = 'ethan.legrand@mail.local'), 'R28', 'son'),
((SELECT id FROM users WHERE email = 'jeanne.guerin@mail.local'), 'R29', 'niece'),
((SELECT id FROM users WHERE email = 'mael.boyer@mail.local'), 'R30', 'nephew'),
((SELECT id FROM users WHERE email = 'lucie.renaud@mail.local'), 'R31', 'daughter'),
((SELECT id FROM users WHERE email = 'sacha.muller@mail.local'), 'R32', 'son'),
((SELECT id FROM users WHERE email = 'nina.henry@mail.local'), 'R33', 'daughter'),
((SELECT id FROM users WHERE email = 'adam.perrin@mail.local'), 'R34', 'son'),
((SELECT id FROM users WHERE email = 'lina.marchand@mail.local'), 'R35', 'granddaughter'),
((SELECT id FROM users WHERE email = 'victor.dufour@mail.local'), 'R36', 'grandson'),
((SELECT id FROM users WHERE email = 'rose.blanchard@mail.local'), 'R37', 'daughter'),
((SELECT id FROM users WHERE email = 'maxime.renard@mail.local'), 'R38', 'son'),
((SELECT id FROM users WHERE email = 'agathe.barbier@mail.local'), 'R39', 'niece'),
((SELECT id FROM users WHERE email = 'baptiste.colin@mail.local'), 'R40', 'nephew');
