persistence true
persistence_location /mosquitto/data/
log_dest stdout

# Port standard (TCP)
listener 1883
allow_anonymous true

# Port WebSockets (Indispensable pour le navigateur !)
listener 9001
protocol websockets
allow_anonymous true